### PR TITLE
Supporting multiple ports exposed by a docker container

### PR DESCRIPTION
**Pull request by alexturek**
Addresses #2 

A template change here requires https://github.com/jwilder/docker-gen/pull/29 to work

### CODE REVIEW

**Comment by nsillik** [comment]
@alexturek I've been looking in to adding similar functionality. Has what you've done here been working for you? I'd love to chat if you have some time and need some help. Thanks!

**Comment by alexturek** [comment]
Yeah, we've been using this change in production for a few months now.
Docker image:
https://registry.hub.docker.com/u/alexturek/docker-register-multiport/

**Comment by themez** [comment]
Why this useful feature not merged yet?

**Comment by gxela** [comment]
+1, I need this!

**Comment by raoofm** [comment]
@jwilder will you be merging these

**Pull request closed without merging**
